### ISSUE TITLE
Support for Elasticsearch 7.0.1?

### ISSUE THREAD

**Issue by abrasat** [bytefish/ElasticSearchExperiment#1]
Could you please update your application to work with Elasticsearch 7.0.1 ?
Thanks!

**Comment by bytefish** [comment]
I will take a look. Basically it should be a matter of updating NEST dependencies and fixing the breaking changes in its API. 😂 I cannot give you a timeframe when I can do it, because I am currently very busy. If you have the time to try it out, feel free to make a Pull Request!

**Comment by bytefish** [comment]
@abrasat I updates the NEST References to 7.0.1-alpha2, and fixed the breaking changes in the code. You can try out if this already works with Elasticsearch 7, I didn't have a chance yet to try.

**Comment by abrasat** [comment]
It works, thank you!

**Comment by bytefish** [comment]
Thanks for the Feedback. I updated the post. Sorry if you got mails for each commit, somehow Github doesn't update the Screenshot, that's why I made so many commits. 🥇
